version: "3.3"

services:
  laracom-user-service:
    container_name: laracom-user-service
    build: ./user-service
    ports:
      - "9000:9000"
    environment:
      MICRO_SERVER_ADDRESS: ":9000"
      MICRO_REGISTRY: "mdns"
      DB_HOST: "laracom-db:3306"
      DB_NAME: "homestead"
      DB_USER: "root"
      DB_PASSWORD: "secret"

networks:
  default:
    external:
      name: laracom-master_laracom-net